# Visualizaciones

In [1]:
import pandas as pd
import altair as alt

In [6]:
from google.colab import files
uploaded = files.upload()

Saving mejorescancionesderock UTF.csv to mejorescancionesderock UTF (1).csv

In [7]:
df = pd.read_csv("mejorescancionesderock UTF (1).csv")

In [39]:
display(df.head())

,Track URI,Track Name,Album Name,Artist Name(s),Release Date,Duration (ms),Popularity,Explicit,Added By,Added At,...,Key,Loudness,Mode,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Time Signature
0,spotify:track:5E8fsTZfvnj7tuRvCnV4SV,Todos Juntos - 2020 Remasterizado,La Ventana (2020 Remasterizado),Los Jaivas,1973-01-01,345096,1,False,12134291227,2024-04-19T20:41:42Z,...,5,-6.547,0,0.0422,0.0697,0.315000,0.0716,0.955,114.210,4
1,spotify:track:15T3otpUnJKin5njR8x0Tx,El Baile De Los Que Sobran,Pateando Piedras,Los Prisioneros,1986-01-01,343701,64,False,12134291227,2024-04-19T20:41:55Z,...,0,-12.274,1,0.0533,0.2970,0.000025,0.1110,0.646,117.331,4
2,spotify:track:1xtBatmC1muBOY1RnUvP8Z,Déjate Caer,La Espada & la Pared,Los Tres,1995,202733,53,False,12134291227,2024-04-19T20:42:08Z,...,0,-8.478,1,0.0284,0.4360,0.000000,0.1270,0.615,115.292,4
3,spotify:track:6hgHu5Cj3fFGMl8DPtZdWS,Baño De Mar A Medianoche,La Incomparable,Cecilia,2006-01-01,193000,44,False,12134291227,2024-04-19T20:42:22Z,...,2,-11.429,0,0.0411,0.7980,0.000000,0.6860,0.534,78.242,4
4,spotify:track:6As9jWGwGowXeSd2OiQzeg,Miño,Canción De Lejos,Los Bunkers,2002,244253,57,False,12134291227,2024-04-19T20:42:33Z,...,0,-4.808,1,0.0292,0.0642,0.000063,0.2480,0.781,105.712,4

In [8]:
df

,Track URI,Track Name,Album Name,Artist Name(s),Release Date,Duration (ms),Popularity,Explicit,Added By,Added At,...,Key,Loudness,Mode,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Time Signature
0,spotify:track:5E8fsTZfvnj7tuRvCnV4SV,Todos Juntos - 2020 Remasterizado,La Ventana (2020 Remasterizado),Los Jaivas,1973-01-01,345096,1,False,12134291227,2024-04-19T20:41:42Z,...,5,-6.547,0,0.0422,0.069700,0.315000,0.0716,0.955,114.210,4
1,spotify:track:15T3otpUnJKin5njR8x0Tx,El Baile De Los Que Sobran,Pateando Piedras,Los Prisioneros,1986-01-01,343701,64,False,12134291227,2024-04-19T20:41:55Z,...,0,-12.274,1,0.0533,0.297000,0.000025,0.1110,0.646,117.331,4
2,spotify:track:1xtBatmC1muBOY1RnUvP8Z,Déjate Caer,La Espada & la Pared,Los Tres,1995,202733,53,False,12134291227,2024-04-19T20:42:08Z,...,0,-8.478,1,0.0284,0.436000,0.000000,0.1270,0.615,115.292,4
3,spotify:track:6hgHu5Cj3fFGMl8DPtZdWS,Baño De Mar A Medianoche,La Incomparable,Cecilia,2006-01-01,193000,44,False,12134291227,2024-04-19T20:42:22Z,...,2,-11.429,0,0.0411,0.798000,0.000000,0.6860,0.534,78.242,4
4,spotify:track:6As9jWGwGowXeSd2OiQzeg,Miño,Canción De Lejos,Los Bunkers,2002,244253,57,False,12134291227,2024-04-19T20:42:33Z,...,0,-4.808,1,0.0292,0.064200,0.000063,0.2480,0.781,105.712,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227,spotify:track:4YdzIFRNNztAB1JF4AltPZ,Ella Llora - Remastered,Que Nos Devuelvan La Emoción (Remastered),Upa!,2020-10-16,287066,0,False,12134291227,2024-04-19T22:23:28Z,...,9,-7.993,1,0.0659,0.148000,0.001470,0.1640,0.782,157.755,4
228,spotify:track:1fwyd3uffoIUVw5FNoWaZg,No Hay Nada Más Feo Que una Mujer Borracha,Lo Normal,Horregias,2017-10-20,192968,0,False,12134291227,2024-04-19T22:23:47Z,...,0,-4.714,1,0.0853,0.000689,0.000156,0.6170,0.622,173.948,4
229,spotify:track:1j0jAzxLglyMQaA4C3oqZs,Perro Rabioso,Round 3,Devil Presley,2007-01-08,131892,34,True,12134291227,2024-04-19T22:23:58Z,...,0,-6.896,1,0.0315,0.018000,0.000002,0.4020,0.440,92.151,4
230,spotify:track:3Yt7vScNXj7VtWeH8Ras00,El Lagarto,I,Alejandro Silva,1999-01-01,186200,17,False,12134291227,2024-04-19T22:24:09Z,...,4,-6.128,1,0.0673,0.000057,0.744000,0.1280,0.749,179.634,4
231,spotify:track:7EdwoFIHkKb5hW2hKMJYri,"La Historia No Me Convence, Solo Me Atraganta",En el Bunker,Fulano,1989-08-18,643213,12,False,12134291227,2024-04-19T22:24:47Z,...,2,-12.304,1,0.0689,0.063500,0.049600,0.0578,0.262,91.268,4

In [9]:
df.columns = df.columns.str.strip()

In [14]:
alt.Chart(df).mark_bar(color="teal").encode(
    x="Track Name:N",
    y="Popularity:Q",
)

alt.Chart(...)

In [47]:
select = alt.selection_point(name="select", on="click")
highlight = alt.selection_point(name="highlight", on="pointerover", empty=False)

In [40]:
import altair as alt

source_filename = "mejorescancionesderock UTF (1).csv"

alt.Chart(df).mark_bar(
    cornerRadiusTopLeft=3,
    cornerRadiusTopRight=3
).encode(
    x='month(Release Date):O',
    y='count():Q',
    color='Artist Name(s):N'
)

alt.Chart(...)

In [42]:
select = alt.selection_point(name="select", on="click")
highlight = alt.selection_point(name="highlight", on="pointerover", empty=False)

In [46]:
!jupyter nbconvert --to html "Visualizaciones.ipynb"

[NbConvertApp] Converting notebook Visualizaciones.ipynb to html
[NbConvertApp] Writing 1042451 bytes to Visualizaciones.html